[project]
name = "batt"
version = "0.1.0"
description = "Battery monitoring and analysis utility for Linux"
requires-python = ">=3.12"
dependencies = ["typer"]

[project.scripts]
batt="batt.cli:app"

[tool.setuptools]
packages = ["batt"]
